### PR TITLE
Add support for the rest of the EventEmitter member functions

### PR DESCRIPTION
**Pull request by TheYarin**
You did a great job, why stop at `on()` and `emit()`?

### CODE REVIEW

**Comment by TheYarin** [comment]
This is not fully working yet.

**Comment by TheYarin** [comment]
Oh, and... I excluded the `eventNames` signature because it is not compatible with `EventEmitter`...
Here's why:
```
Type 'EventEmitter' is not assignable to type 'TypeSafeEventEmitter<Events>'.
  The types returned by 'eventNames()' are incompatible between these types.
    Type '(string | symbol)[]' is not assignable to type 'K[]'.
      Type 'string | symbol' is not assignable to type 'K'.
        'K' could be instantiated with an arbitrary type which could be unrelated to 'string | symbol'.ts(2322)
```

**Comment by sorribas** [comment]
Hi thanks for the PR. I only added `on` and `emit` because it's what I needed at the time. But of course it would be cool to have all methods working. Let me know when it's fully working :).

Also do you mind removing the semicolons? I generally don't use semicolons in my code and would like to keep it that way.

**Comment by TheYarin** [comment]
Sure, Prettier did that automatically, I'll remove those.

**Comment by TheYarin** [comment]
Here, I added all the member methods except for `eventNames` which doesn't fit as nicely into this typing structure.

**Comment by sorribas** [comment]
Looks good. Thank you

**Comment by sorribas** [comment]
Published 1.1.0

**Pull request merged**
